### ISSUE TITLE
Random InvalidArgumentException on Admin panel

### ISSUE THREAD

**Issue by TristanPct** [getgrav/grav-plugin-admin#1214]
Hello folks, 

I have a strange error on my admin panel:
```
Uncaught InvalidArgumentException: 'C:/xampp/system/assets' is not a valid directory in D:\Projets\www\jade\vendor\filp\whoops\src\Whoops\Handler\PrettyPageHandler.php:552
Stack trace:
#0 D:\Projets\www\jade\system\src\Grav\Common\Errors\Errors.php(40): Whoops\Handler\PrettyPageHandler->addResourcePath('C:/xampp/system...')
#1 D:\Projets\www\jade\system\src\Grav\Common\Processors\ErrorsProcessor.php(18): Grav\Common\Errors\Errors->resetHandlers()
#2 D:\Projets\www\jade\system\src\Grav\Common\Grav.php(132): Grav\Common\Processors\ErrorsProcessor->process()
#3 D:\Projets\www\jade\system\src\Grav\Common\Grav.php(379): Grav\Common\Grav->Grav\Common\{closure}()
#4 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('_errors', 'Error Handlers ...', Object(Closure))
#5 D:\Projets\www\jade\system\src\Grav\Common\Grav.php(355): call_user_func_array(Object(Closure), Array)
#6 D:\Projets\www\jade\system\src\Grav\Common\Grav.php(133): Grav\Common\Grav->__call('measureTime', Array)
#7 D:\Projets\www\jade\index.ph in D:\Projets\www\jade\vendor\filp\whoops\src\Whoops\Handler\PrettyPageHandler.php on line 552
```

It's happend randomly (on the first admin page or when savinga new page) and it's not a blocking error, page are saved correctly.

I run my grave website on a local server (Windows 10 Pro + xampp).

One thing that can lead this error is that my web root folder is `D:\Projets\www` and the xampp root folder is `C:\xampp\htdocs` (with `htdocs` a sym link to `D:\Projets\www`).

**Comment by rhukster** [comment]
Only thing I can think of is that its a windows symlink inconsistency with folders linked between physical drives.  I use symlinks extensively on my mac and have never had an issue.  Can you replicate this if your symlinks are on the same drive?
