### ISSUE TITLE
issues with core-service-manager after installing plugins thru grav-plugin-admin

### ISSUE THREAD

**Issue by supermorph** [getgrav/grav-plugin-admin#1431]
'core-service-manager' crashes the site backend if installed.

if i remove the folder for it, the site says

'Missing dependency: 'core-service-manager'
Plugin 'Admin Power Tools' was not loaded due to dependency issues
Plugin 'Editor' was not loaded due to dependency issues'

soon as i put the folder back it says:

'
Server Error

Sorry, something went terribly wrong!
E_NOTICE - Indirect modification of overloaded property Twelvetone\Common\ServiceInfo::$implementation has no effect
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.'

this has just popped up, and wasnt the original error

i cannot get back to the page it shown me but heres the bit from the log (looks very un-organised but hope it helps understand what happened)

" [2018-04-24 13:41:55] grav.CRITICAL: Indirect modification of overloaded property Twelvetone\Common\ServiceInfo::$implementation has no effect - Trace: #0 C:\Program~1\wamp\www\getgrav\user\plugins\core-service-manager\core-service-manager.php(84): Whoops\Run->handleError(8, 'Indirect modifi...', 'C:\\Program~1\\wa...', 84, Array) #1 C:\Program~1\wamp\www\getgrav\user\plugins\core-service-manager\classes\ServiceManager.php(387): Grav\Plugin\CoreServiceManagerPlugin->Grav\Plugin\{closure}(Object(Twelvetone\Common\ServiceInfo)) #2 C:\Program~1\wamp\www\getgrav\user\plugins\core-service-manager\classes\ServiceManager.php(116): Twelvetone\Common\ServiceManager->notifyListeners('asset', Object(Twelvetone\Common\ServiceInfo)) #3 C:\Program~1\wamp\www\getgrav\user\plugins\editor\editor.php(150): Twelvetone\Common\ServiceManager->registerService('asset', Array) #4 [internal function]: Grav\Plugin\EditorPlugin->onAdminMenu(Object(RocketTheme\Toolbox\Event\Event), 'onAdminMenu', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #5 C:\Program~1\wamp\www\getgrav\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onAdminMenu', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #6 C:\Program~1\wamp\www\getgrav\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onAdminMenu', Object(RocketTheme\Toolbox\Event\Event)) #7 C:\Program~1\wamp\www\getgrav\vendor\rockettheme\toolbox\Event\src\EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onAdminMenu', Object(RocketTheme\Toolbox\Event\Event)) #8 C:\Program~1\wamp\www\getgrav\system\src\Grav\Common\Grav.php(283): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onAdminMenu', NULL) #9 C:\Program~1\wamp\www\getgrav\user\plugins\admin\admin.php(523): Grav\Common\Grav->fireEvent('onAdminMenu') #10 [internal function]: Grav\Plugin\AdminPlugin->onTwigSiteVariables(Object(RocketTheme\Toolbox\Event\Event), 'onTwigSiteVaria...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #11 C:\Program~1\wamp\www\getgrav\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onTwigSiteVaria...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #12 C:\Program~1\wamp\www\getgrav\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onTwigSiteVaria...', Object(RocketTheme\Toolbox\Event\Event)) #13 C:\Program~1\wamp\www\getgrav\vendor\rockettheme\toolbox\Event\src\EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onTwigSiteVaria...', Object(RocketTheme\Toolbox\Event\Event)) #14 C:\Program~1\wamp\www\getgrav\system\src\Grav\Common\Grav.php(283): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onTwigSiteVaria...', NULL) #15 C:\Program~1\wamp\www\getgrav\system\src\Grav\Common\Twig\Twig.php(324): Grav\Common\Grav->fireEvent('onTwigSiteVaria...') #16 C:\Program~1\wamp\www\getgrav\system\src\Grav\Common\Service\OutputServiceProvider.php(27): Grav\Common\Twig\Twig->processSite('html') #17 C:\Program~1\wamp\www\getgrav\vendor\pimple\pimple\src\Pimple\Container.php(118): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #18 C:\Program~1\wamp\www\getgrav\system\src\Grav\Common\Processors\RenderProcessor.php(19): Pimple\Container->offsetGet('output') #19 C:\Program~1\wamp\www\getgrav\system\src\Grav\Common\Grav.php(132): Grav\Common\Processors\RenderProcessor->process() #20 C:\Program~1\wamp\www\getgrav\system\src\Grav\Common\Grav.php(374): Grav\Common\Grav->Grav\Common\{closure}() #21 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('render', 'Render', Object(Closure)) #22 C:\Program~1\wamp\www\getgrav\system\src\Grav\Common\Grav.php(350): call_user_func_array(Object(Closure), Array) #23 C:\Program~1\wamp\www\getgrav\system\src\Grav\Common\Grav.php(133): Grav\Common\Grav->__call('measureTime', Array) #24 C:\Program~1\wamp\www\getgrav\system\src\Grav\Common\Grav.php(133): Grav\Common\Grav->measureTime('render', 'Render', Object(Closure)) #25 C:\Program~1\wamp\www\getgrav\index.php(52): Grav\Common\Grav->process() #26 {main} [] []" 

system and server info as follows:
wamp 64bit 3.10
PHP Version 5.6.31
Apache Version 2.4.27
running on Windows 10 pro x64 (my own pc for now)
32GB ddr3
amd FX 9590
amd rx 580-8GB
windows 10 is installed to a dedicated 1TB hdd 
(i have other drives too but for the sake of easy-info they are not used within this setup)

wamp is installed in " c:\program~1\wamp "
grav is a fresh clean install.

plugins i installed manually to see what would work without the errornous core-service-manager im having the issue with:

absalomedia-grav-plugin-grava11y-1.0.2-0-gfbf074f.zip
aradianoff-recaptchacontact-v2.1.2-0-ge755633.zip
clemdesign-grav-plugin-adsense2-1.1.1-0-gade89f7.zip
cworreschk-grav-plugin-qrcode-v1.1.0-0-gb412383.zip
david-szabo97-grav-plugin-admin-addon-user-manager-2.1.5-0-gfc496ca.zip
dimitrilongo-grav-plugin-mobile-detect-v1.3.2-0-ga5e0bc2.zip
Diyzzuf-grav-plugin-private-v1.0.9-0-ge83d218.zip
Flamenco-admin-power-tools-0.1.4-0-gfce3648.zip
Flamenco-grav-plugin-core-service-manager-1.0.8-0-gb8eee32(1).zip
Flamenco-grav-plugin-core-service-manager-1.0.8-0-gb8eee32.zip
Flamenco-grav-plugin-editor-0.1.2-0-g47a9afc.zip
Flamenco-grav-plugin-quicksave-0.1.7-0-g5d77240.zip
flaviocopes-grav-plugin-shoppingcart-1.2.2-0-gabd9c64.zip
gameamea-grav-plugin-autoseo-1.3.5-0-g73abf6d.zip
getgrav-grav-plugin-data-manager-1.2.0-0-g7f10c43.zip
getgrav-grav-plugin-form-2.13.3-0-gc4e85e8.zip
getgrav-grav-plugin-login-2.6.3-0-g05afc8d.zip
getgrav-grav-plugin-youtube-2.0.4-0-gd7eab0b.zip
grav-admin-v1.4.3.zip
grav-pkg_gantry5_v5.4.23.zip
grav-skeleton-photographer-site-v1.0.3.zip
grav-skeleton-woo-site-v1.0.1(1).zip
grav-skeleton-woo-site-v1.0.1.zip
hugoaf-grav-plugin-logerrors-1.0.1-0-gfa420a5.zip
newbthenewbd-grav-plugin-tinymce-editor-v1.1.7-0-g6457577.zip
OleVik-grav-plugin-directorylisting-v1.1.1-0-gc727ac3.zip
Perlkonig-grav-plugin-graveyard-v1.1.0-0-g6e28ada.zip
Sommerregen-grav-plugin-mediaembed-v1.3.0-0-g555aad3.zip
urbansquidlondon-grav-plugin-squid-backup-v1.0.4-0-g329075d.zip

i have tried to be as detailed as possible, and also make the problem easy-to-read, hope ive done enough.

thanks for any assistance

**Comment by supermorph** [comment]
have done more tests

i removed admin power tools, core-service-manager, and editor

, i then used the admin panel to re-install core-service-manager (it did not fail or crash the backend)
then i installed admin power tools (it also worked, no errors)

then, i installed editor, after install, the main problem came back up.

so i can say while i can work around the issue, it seems to be an issue with these 3 items somewhere.

hope this helps
