### ISSUE TITLE
Call to undefined method Grav\Common\GPM\Response::getManual()

### ISSUE THREAD

**Issue by bsheen** [getgrav/grav-plugin-admin#1434]
I'm getting the above error when trying to access the admin plugin. 

I've tried:
- Upgrading the Admin plugin
- Upgrading Grav
- Switching the template from our custom one to Quark
- Set enable_auto_updates_check to false in admin.yaml

```
Error thrown with message "Call to undefined method Grav\Common\GPM\Response::getManual()"

Stacktrace:
#38 Error in /usr/share/nginx/html/system/src/Grav/Common/GPM/Response.php:179
#37 Grav\Common\GPM\Response:get in /usr/share/nginx/html/system/src/Grav/Common/GPM/Remote/AbstractPackageCollection.php:68
#36 Grav\Common\GPM\Remote\AbstractPackageCollection:fetch in /usr/share/nginx/html/system/src/Grav/Common/GPM/Remote/AbstractPackageCollection.php:54
#35 Grav\Common\GPM\Remote\AbstractPackageCollection:__construct in /usr/share/nginx/html/system/src/Grav/Common/GPM/Remote/Plugins.php:27
#34 Grav\Common\GPM\Remote\Plugins:__construct in /usr/share/nginx/html/system/src/Grav/Common/GPM/Remote/Packages.php:18
#33 Grav\Common\GPM\Remote\Packages:__construct in /usr/share/nginx/html/system/src/Grav/Common/GPM/GPM.php:58
#32 Grav\Common\GPM\GPM:__construct in /usr/share/nginx/html/user/plugins/admin/classes/admin.php:797
#31 Grav\Plugin\Admin\Admin:gpm in /usr/share/nginx/html/user/plugins/admin/classes/admin.php:824
#30 Grav\Plugin\Admin\Admin:plugins in /usr/share/nginx/html/vendor/twig/twig/lib/Twig/Template.php:677
#29 Twig_Template:getAttribute in /usr/share/nginx/html/cache/twig/56/56a9e1214e2bb37cb193d359b3f3fb692fcfc0aefed1b4bfa732f489286a5bb3.php:193
#28 __TwigTemplate_0769d2f908640f86801a79da80ddd70fa285ea06e0b4178b7409108471d0d088:doDisplay in /usr/share/nginx/html/vendor/twig/twig/lib/Twig/Template.php:432
#27 Twig_Template:displayWithErrorHandling in /usr/share/nginx/html/vendor/twig/twig/lib/Twig/Template.php:403
#26 Twig_Template:display in /usr/share/nginx/html/cache/twig/d7/d7cd4d39ee77438145bce136f6f2d0795698d82f324e7b39d60f645fda03e263.php:220
#25 __TwigTemplate_23ca62f96c30e282cecf4555045b08c607c715f0fea291c100c8bcf0a20f46df:block_navigation in /usr/share/nginx/html/vendor/twig/twig/lib/Twig/Template.php:215
#24 Twig_Template:displayBlock in /usr/share/nginx/html/cache/twig/d7/d7cd4d39ee77438145bce136f6f2d0795698d82f324e7b39d60f645fda03e263.php:184
#23 __TwigTemplate_23ca62f96c30e282cecf4555045b08c607c715f0fea291c100c8bcf0a20f46df:block_page in /usr/share/nginx/html/vendor/twig/twig/lib/Twig/Template.php:215
#22 Twig_Template:displayBlock in /usr/share/nginx/html/cache/twig/d7/d7cd4d39ee77438145bce136f6f2d0795698d82f324e7b39d60f645fda03e263.php:167
#21 __TwigTemplate_23ca62f96c30e282cecf4555045b08c607c715f0fea291c100c8bcf0a20f46df:block_body in /usr/share/nginx/html/vendor/twig/twig/lib/Twig/Template.php:215
#20 Twig_Template:displayBlock in /usr/share/nginx/html/cache/twig/d7/d7cd4d39ee77438145bce136f6f2d0795698d82f324e7b39d60f645fda03e263.php:52
#19 __TwigTemplate_23ca62f96c30e282cecf4555045b08c607c715f0fea291c100c8bcf0a20f46df:doDisplay in /usr/share/nginx/html/vendor/twig/twig/lib/Twig/Template.php:432
#18 Twig_Template:displayWithErrorHandling in /usr/share/nginx/html/vendor/twig/twig/lib/Twig/Template.php:403
#17 Twig_Template:display in /usr/share/nginx/html/cache/twig/1f/1f67d8b31ffc2013f37d24172c3f097213af03b1e2499691795f1ab50add6319.php:23
#16 __TwigTemplate_77c9fceb1d0823e88ddb0abf904fc7dccdb4ba9d396a8a9f6b91c2301b52c284:doDisplay in /usr/share/nginx/html/vendor/twig/twig/lib/Twig/Template.php:432
#15 Twig_Template:displayWithErrorHandling in /usr/share/nginx/html/vendor/twig/twig/lib/Twig/Template.php:403
#14 Twig_Template:display in /usr/share/nginx/html/cache/twig/20/20d6f8b6eba1a9346d926f6b2e47b9bcd17b0701d16a1e1eaee789b5e40081ce.php:32
#13 __TwigTemplate_81659c9834c497c66464f0c22ede3764debaeabf55885c792e2606e7cd838507:doDisplay in /usr/share/nginx/html/vendor/twig/twig/lib/Twig/Template.php:432
#12 Twig_Template:displayWithErrorHandling in /usr/share/nginx/html/vendor/twig/twig/lib/Twig/Template.php:403
#11 Twig_Template:display in /usr/share/nginx/html/vendor/twig/twig/lib/Twig/Template.php:411
#10 Twig_Template:render in /usr/share/nginx/html/vendor/twig/twig/lib/Twig/Environment.php:363
#9 Twig_Environment:render in /usr/share/nginx/html/system/src/Grav/Common/Twig/Twig.php:349
#8 Grav\Common\Twig\Twig:processSite in /usr/share/nginx/html/system/src/Grav/Common/Service/OutputServiceProvider.php:27
#7 Grav\Common\Service\OutputServiceProvider:Grav\Common\Service\{closure} in /usr/share/nginx/html/vendor/pimple/pimple/src/Pimple/Container.php:118
#6 Pimple\Container:offsetGet in /usr/share/nginx/html/system/src/Grav/Common/Processors/RenderProcessor.php:19
#5 Grav\Common\Processors\RenderProcessor:process in /usr/share/nginx/html/system/src/Grav/Common/Grav.php:132
#4 Grav\Common\Grav:Grav\Common\{closure} in /usr/share/nginx/html/system/src/Grav/Common/Grav.php:374
#3 Grav\Common\Grav:Grav\Common\{closure} in /usr/share/nginx/html/system/src/Grav/Common/Grav.php:350
#2 call_user_func_array in /usr/share/nginx/html/system/src/Grav/Common/Grav.php:350
#1 Grav\Common\Grav:__call in /usr/share/nginx/html/system/src/Grav/Common/Grav.php:133
#0 Grav\Common\Grav:process in /usr/share/nginx/html/index.php:52
```

It's worth noting that I'm getting a similar message from:
`bin/gpm self-upgrade`

```
PHP Fatal error:  Uncaught Error: Call to undefined method Grav\Common\GPM\Response::getManual() in /usr/share/nginx/html/system/src/Grav/Common/GPM/Response.php:179
Stack trace:
#0 /usr/share/nginx/html/system/src/Grav/Common/GPM/Remote/AbstractPackageCollection.php(68): Grav\Common\GPM\Response::get('https://getgrav...', Array, NULL)
#1 /usr/share/nginx/html/system/src/Grav/Common/GPM/Remote/GravCore.php(36): Grav\Common\GPM\Remote\AbstractPackageCollection->fetch(false, NULL)
#2 /usr/share/nginx/html/system/src/Grav/Common/GPM/Upgrader.php(38): Grav\Common\GPM\Remote\GravCore->__construct(false, NULL)
#3 /usr/share/nginx/html/system/src/Grav/Console/Gpm/SelfupgradeCommand.php(90): Grav\Common\GPM\Upgrader->__construct(false)
#4 /usr/share/nginx/html/system/src/Grav/Console/ConsoleCommand.php(29): Grav\Console\Gpm\SelfupgradeCommand->serve()
#5 /usr/share/nginx/html/vendor/symfony/console/Command/Command.php(242): Grav\Console\ConsoleCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component in /usr/share/nginx/html/system/src/Grav/Common/GPM/Response.php on line 179
```

**Comment by rhukster** [comment]
Hmm.. i can't replicate this, so it looks like something is way out of date.  How about manually downloading the Grav package and copying 'over' your current Grav install to ensure you have all the latest files? https://github.com/getgrav/grav/releases/download/1.4.3/grav-update-v1.4.3.zip

**Comment by bsheen** [comment]
Turns out it was:
`method: manual`
in `user/config/systems.yaml`
```
 gpm:
   releases: stable
   method: manual
   verify_peer: true
   official_gpm_only: true
```
it was changed from:
`method: auto`
what are the valid options for `method`? (nothing is outlined here (https://learn.getgrav.org/basics/grav-configuration#gpm) 

It is worth noting that the issue (granted it is possibly PEBKAC issue) exists under both versions tested as outlined below.
`bin/grav --version`
Grav CLI Application version 1.3.10
then upgrading via:
`bin/gpm self-upgrade`
gives:
`bin/grav --version`
Grav CLI Application version 1.4.3

**Comment by rhukster** [comment]
I've updated the docs.
