### ISSUE TITLE
Grav v1.6.21 breaks on PHP 7.4? (E_NOTICE - Trying to access array offset on value of type null)

### ISSUE THREAD

**Issue by ulfben** [getgrav/grav-plugin-admin#1835]
I'm running Grav v1.6.21 on Ubuntu 18.04. After upgrading PHP to 7.4.3 the site broke - when loading the front page I get: 

### E_NOTICE - Trying to access array offset on value of type null

The log says:
    [2020-02-20 21:51:58] grav.CRITICAL: Trying to access array offset on value of type null - Trace: 
    #0 /var/www/infoscreen/system/src/Grav/Common/Debugger.php(352): Whoops\Run->handleError() 
    #1 /var/www/infoscreen/vendor/erusev/parsedown-extra/ParsedownExtra.php(241): Grav\Common\Debugger->deprecatedErrorHandler() 
    #2 /var/www/infoscreen/vendor/erusev/parsedown/Parsedown.php(206): ParsedownExtra->blockSetextHeader() 
    #3 /var/www/infoscreen/vendor/erusev/parsedown/Parsedown.php(39): Parsedown->lines() 
    #4 /var/www/infoscreen/vendor/erusev/parsedown-extra/ParsedownExtra.php(46): Parsedown->text() 
    #5 /var/www/infoscreen/system/src/Grav/Common/Page/Page.php(849): ParsedownExtra->text() 
    #6 /var/www/infoscreen/system/src/Grav/Common/Page/Page.php(692): Grav\Common\Page\Page->processMarkdown() 
    #7 /var/www/infoscreen/system/src/Grav/Common/Twig/Twig.php(366): Grav\Common\Page\Page->content() 
    #8 /var/www/infoscreen/system/src/Grav/Common/Service/OutputServiceProvider.php(28): Grav\Common\Twig\Twig->processSite() 
    #9 /var/www/infoscreen/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}() 
    #10 /var/www/infoscreen/system/src/Grav/Common/Processors/RenderProcessor.php(28): Pimple\Container->offsetGet() 
    #11 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RenderProcessor->process() 
    #12 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle()
    #13 /var/www/infoscreen/system/src/Grav/Common/Processors/DebuggerAssetsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #14 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\DebuggerAssetsProcessor->process()
    #15 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #16 /var/www/infoscreen/system/src/Grav/Common/Processors/PagesProcessor.php(69): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #17 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PagesProcessor->process() 
    #18 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle()
    #19 /var/www/infoscreen/system/src/Grav/Common/Processors/TwigProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle()
    #20 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TwigProcessor->process()
    #21 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #22 /var/www/infoscreen/system/src/Grav/Common/Processors/AssetsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #23 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\AssetsProcessor->process()
    #24 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #25 /var/www/infoscreen/system/src/Grav/Common/Processors/SchedulerProcessor.php(29): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #26 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\SchedulerProcessor->process() 
    #27 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #28 /var/www/infoscreen/system/src/Grav/Common/Processors/BackupsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #29 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\BackupsProcessor->process()
    #30 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle()
    #31 /var/www/infoscreen/system/src/Grav/Common/Processors/TasksProcessor.php(59): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #32 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TasksProcessor->process() 
    #33 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #34 /var/www/infoscreen/system/src/Grav/Common/Processors/RequestProcessor.php(52): Grav\Framework\RequestHandler\RequestHandler->handle()
    #35 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RequestProcessor->process()
    #36 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle()
    #37 /var/www/infoscreen/system/src/Grav/Common/Processors/ThemesProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #38 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ThemesProcessor->process()
    #39 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle()
    #40 /var/www/infoscreen/system/src/Grav/Common/Processors/PluginsProcessor.php(30): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #41 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PluginsProcessor->process() 
    #42 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle()
    #43 /var/www/infoscreen/system/src/Grav/Common/Processors/InitializeProcessor.php(95): Grav\Framework\RequestHandler\RequestHandler->handle()
    #44 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\InitializeProcessor->process() 
    #45 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #46 /var/www/infoscreen/system/src/Grav/Common/Processors/DebuggerProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #47 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\DebuggerProcessor->process()
    #48 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle()
    #49 /var/www/infoscreen/system/src/Grav/Common/Processors/ErrorsProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #50 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ErrorsProcessor->process()
    #51 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #52 /var/www/infoscreen/system/src/Grav/Common/Processors/LoggerProcessor.php(48): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #53 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\LoggerProcessor->process() 
    #54 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #55 /var/www/infoscreen/system/src/Grav/Common/Processors/ConfigurationProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #56 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ConfigurationProcessor->process() 
    #57 /var/www/infoscreen/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #58 /var/www/infoscreen/system/src/Grav/Common/Grav.php(272): Grav\Framework\RequestHandler\RequestHandler->handle()
    #59 /var/www/infoscreen/index.php(54): Grav\Common\Grav->process() 
    #60 {main} [] []

All plugins are up-to-date, and I've tried disabling them all but the problem persist. 

Is this an issue on my end, and if so, how do I trouble-shoot?

**Comment by ulfben** [comment]
Sorry! Posted on the wrong repo. Can't see a way to delete this so I'll just close it.
