### ISSUE TITLE
Can't open Configuration page: "Array to string conversion" exception

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-admin#2081]
Just updated from Grav 1.6 to 1.7 and latest Admin plugin. All works fine but now I can't open Configuration page.

Any ideas how to fix?

grav.log:
```

[2021-02-21 23:15:21] grav.CRITICAL: An exception has been thrown during the rendering of a template ("Array to string conversion"). - Trace: 
#0 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(379): Twig\Template->displayBlock('input', Array, Array) 
#1 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(214): __TwigTemplate_123156e365d1a51139f4587e391161bc5a9b635e5e5f5a47c631b2f61aacdcdc->block_group(Array, Array) 
#2 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(251): Twig\Template->displayBlock('group', Array, Array) 
#3 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(214): __TwigTemplate_123156e365d1a51139f4587e391161bc5a9b635e5e5f5a47c631b2f61aacdcdc->block_contents(Array, Array) 
#4 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(142): Twig\Template->displayBlock('contents', Array, Array) 
#5 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(214): __TwigTemplate_123156e365d1a51139f4587e391161bc5a9b635e5e5f5a47c631b2f61aacdcdc->block_field(Array, Array) 
#6 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(111): Twig\Template->displayBlock('field', Array, Array) 
#7 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(453): __TwigTemplate_123156e365d1a51139f4587e391161bc5a9b635e5e5f5a47c631b2f61aacdcdc->doDisplay(Array, Array) 
#8 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) 
#9 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(57): Twig\Template->display(Array, Array) 
#10 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(453): __TwigTemplate_e80770ac18f957aedef3047af409c7834f5e22cb34576c91b57be9b0a4c8c18c->doDisplay(Array, Array) 
#11 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) 
#12 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(118): Twig\Template->display(Array) #13 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(214): __TwigTemplate_e93a81715757348c49a0e5ed8a60f1ab3cb8f8f3519d37a07a41c16f0ee43264->block_field(Array, Array) 
#14 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(75): Twig\Template->displayBlock('field', Array, Array) #15 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(453): __TwigTemplate_e93a81715757348c49a0e5ed8a60f1ab3cb8f8f3519d37a07a41c16f0ee43264->doDisplay(Array, Array) 
#16 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #17 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(57): Twig\Template->display(Array) #18 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(214): __TwigTemplate_a66fb72f6123e22a4fa85280f397a2c844111802a12c7bd7c6b0a6ca6fdab357->block_field(Array, Array) #19 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(111): Twig\Template->displayBlock('field', Array, Array) #20 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(453): __TwigTemplate_123156e365d1a51139f4587e391161bc5a9b635e5e5f5a47c631b2f61aacdcdc->doDisplay(Array, Array) #21 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #22 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(38): Twig\Template->display(Array, Array) #23 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(453): __TwigTemplate_a66fb72f6123e22a4fa85280f397a2c844111802a12c7bd7c6b0a6ca6fdab357->doDisplay(Array, Array) 
#24 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #25 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(118): Twig\Template->display(Array) #26 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(214): __TwigTemplate_e93a81715757348c49a0e5ed8a60f1ab3cb8f8f3519d37a07a41c16f0ee43264->block_field(Array, Array) #27 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(75): Twig\Template->displayBlock('field', Array, Array) #28 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(453): __TwigTemplate_e93a81715757348c49a0e5ed8a60f1ab3cb8f8f3519d37a07a41c16f0ee43264->doDisplay(Array, Array) 
#29 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #30 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(384): Twig\Template->display(Array, Array) #31 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(453): __TwigTemplate_eb19a87200035bd07197b7a9ac73277aca10cb928616d9ae9384e26638e3a019___1685923316->doDisplay(Array, Array) #32 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #33 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(249): Twig\Template->display(Array) #34 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(214): __TwigTemplate_eb19a87200035bd07197b7a9ac73277aca10cb928616d9ae9384e26638e3a019->block_field(Array, Array) #35 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(111): Twig\Template->displayBlock('field', Array, Array) #36 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(453): __TwigTemplate_123156e365d1a51139f4587e391161bc5a9b635e5e5f5a47c631b2f61aacdcdc->doDisplay(Array, Array) 
#37 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #38 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(46): Twig\Template->display(Array, Array) #39 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(453): __TwigTemplate_eb19a87200035bd07197b7a9ac73277aca10cb928616d9ae9384e26638e3a019->doDisplay(Array, Array) #40 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #41 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(99): Twig\Template->display(Array) #42 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(453): __TwigTemplate_1a7cff06665753a88299328048ebedf11d53e0da01e2e4321ef8011534014409->doDisplay(Array, Array) #43 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #44 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(241): Twig\Template->display(Array) #45 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(214): __TwigTemplate_791d1e19666ee67bbd7bc8d68e45b9ee87665fc1586dd2e7ec9909e445e31807->block_content(Array, Array) #46 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(374): Twig\Template->displayBlock('content', Array, Array) #47 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(214): __TwigTemplate_6eb1f40af31251af39683d98bf1e78b23e3755cb46bf28d84ae291115dd95b60->block_content_wrapper(Array, Array) #48 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(300): Twig\Template->displayBlock('content_wrapper', Array, Array) #49 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(214): __TwigTemplate_6eb1f40af31251af39683d98bf1e78b23e3755cb46bf28d84ae291115dd95b60->block_page(Array, Array) #50 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(254): Twig\Template->displayBlock('page', Array, Array) #51 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(214): __TwigTemplate_6eb1f40af31251af39683d98bf1e78b23e3755cb46bf28d84ae291115dd95b60->block_body(Array, Array) #
52 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(78): Twig\Template->displayBlock('body', Array, Array) #53 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(453): __TwigTemplate_6eb1f40af31251af39683d98bf1e78b23e3755cb46bf28d84ae291115dd95b60->doDisplay(Array, Array) #54 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #55 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(37): Twig\Template->display(Array, Array) #56 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(453): __TwigTemplate_fa866f06596fc3b9768f9db4573a83053beffa0710036a7f4918c7c6601b9f5d->doDisplay(Array, Array) 
#57 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #58 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(497) : eval()'d code(65): Twig\Template->display(Array, Array) #59 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(453): __TwigTemplate_791d1e19666ee67bbd7bc8d68e45b9ee87665fc1586dd2e7ec9909e445e31807->doDisplay(Array, Array) 
#60 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #61 /Users/artyom/domains/pepel/vendor/twig/twig/src/Template.php(432): Twig\Template->display(Array) #62 /Users/artyom/domains/pepel/vendor/twig/twig/src/TemplateWrapper.php(47): Twig\Template->render(Array, Array) #63 /Users/artyom/domains/pepel/vendor/twig/twig/src/Environment.php(384): Twig\TemplateWrapper->render(Array) #64 /Users/artyom/domains/pepel/system/src/Grav/Common/Twig/Twig.php(403): Twig\Environment->render('config.html.twi...', Array) #65 /Users/artyom/domains/pepel/system/src/Grav/Common/Service/OutputServiceProvider.php(36): Grav\Common\Twig\Twig->processSite('html') #66 /Users/artyom/domains/pepel/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #67 /Users/artyom/domains/pepel/system/src/Grav/Common/Processors/RenderProcessor.php(39): Pimple\Container->offsetGet('output') #68 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\RenderProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #69 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #70 /Users/artyom/domains/pepel/system/src/Grav/Common/Processors/DebuggerAssetsProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #71 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\DebuggerAssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #72 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #73 /Users/artyom/domains/pepel/system/src/Grav/Common/Processors/PagesProcessor.php(81): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #74 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PagesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #75 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #76 /Users/artyom/domains/pepel/system/src/Grav/Common/Processors/TwigProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #77 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\TwigProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #78 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #79 /Users/artyom/domains/pepel/system/src/Grav/Common/Processors/AssetsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #80 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\AssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #81 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #82 /Users/artyom/domains/pepel/system/src/Grav/Common/Processors/SchedulerProcessor.php(40): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #83 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\SchedulerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #84 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #85 /Users/artyom/domains/pepel/system/src/Grav/Common/Processors/BackupsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #86 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\BackupsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #87 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #88 /Users/artyom/domains/pepel/system/src/Grav/Common/Processors/TasksProcessor.php(69): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #89 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\TasksProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #90 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #91 /Users/artyom/domains/pepel/user/plugins/admin/classes/plugin/Router.php(51): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #92 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Plugin\Admin\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #93 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) 
#94 /Users/artyom/domains/pepel/system/src/Grav/Common/Processors/RequestProcessor.php(63): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #95 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\RequestProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #96 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #97 /Users/artyom/domains/pepel/system/src/Grav/Common/Processors/ThemesProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) 
#98 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\ThemesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #99 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #100 /Users/artyom/domains/pepel/system/src/Grav/Common/Processors/PluginsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #101 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PluginsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #102 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) 
#103 /Users/artyom/domains/pepel/system/src/Grav/Common/Processors/InitializeProcessor.php(129): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) 
#104 /Users/artyom/domains/pepel/system/src/Grav/Common/Debugger.php(546): Grav\Common\Processors\InitializeProcessor::Grav\Common\Processors\{closure}() #105 /Users/artyom/domains/pepel/system/src/Grav/Common/Processors/InitializeProcessor.php(130): Grav\Common\Debugger->profile(Object(Closure)) #106 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\InitializeProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #107 /Users/artyom/domains/pepel/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #108 /Users/artyom/domains/pepel/system/src/Grav/Common/Grav.php(295): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #109 /Users/artyom/domains/pepel/index.php(58): Grav\Common\Grav->process() #110 {main} [] []

```

**Comment by mahagr** [comment]
Search the files in `cache/twig/` for `__TwigTemplate_123156e365d1a51139f4587e391161bc5a9b635e5e5f5a47c631b2f61aacdcdc` and open the file which contains the class. It should have a comment just before the class telling the twig file. It should help us to figure out what is going wrong.

**Comment by Sogl** [comment]
No `cache/twig` folder:
![image](https://user-images.githubusercontent.com/7556290/108688703-43591880-7509-11eb-8c87-f7a349c6fd54.png)

**Comment by Sogl** [comment]
And also I can't clear "All cache" from admin Dashboard:
![image](https://user-images.githubusercontent.com/7556290/108689210-dc882f00-7509-11eb-9737-2fa32640b3b4.png)

**Comment by mahagr** [comment]
Umm, I have no idea what is going on. Try deleting manually all the files in cache folder..?

**Comment by Sogl** [comment]
Done but the same error.

**Comment by mahagr** [comment]
Can you search the template file that is erroring out?

Also check `config/streams.yaml` or if you have `setup.php` for the cache stream.

**Comment by Sogl** [comment]
> Can you search the template file that is erroring out?

I tried to find files like `__TwigTemplate_123156e365d1a51139f4587e391161bc5a9b635e5e5f5a47c631b2f61aacdcdc` but they are not found anywhere.

>Also check config/streams.yaml or if you have setup.php for the cache stream.

I don't have this file.
![image](https://user-images.githubusercontent.com/7556290/108844633-6e1c9d00-75ed-11eb-8f3a-13e278f8ab1a.png)

**Comment by mahagr** [comment]
The string to search is inside some file in `cache/twig` folder. You need to search all the files to find the content.

Which operating system are you using?

**Comment by Sogl** [comment]
>The string to search is inside some file in cache/twig folder. You need to search all the files to find the content.

I have no `cache/twig` folder:
![image](https://user-images.githubusercontent.com/7556290/108851124-2568e200-75f5-11eb-8489-02dd883bd434.png)

>Which operating system are you using?

Mac OS Catalina 10.15.7

**Comment by rhukster** [comment]
BTW, what version of PHP are you on?  Do you have YAML and Twig compatibility ON in the System -> Advanced settings in the admin? Try that if not.

**Comment by mahagr** [comment]
Also, make sure that Twig caching is always turned on (disabling it just makes the site super slow without any benefits).

Also check if the `system.yaml` file looks ok for you, there was a bug in the previous release where it was corrupted if you switched templates in admin.

**Comment by Sogl** [comment]
>BTW, what version of PHP are you on? 

PHP 7.4.15

>Do you have YAML and Twig compatibility ON in the System -> Advanced settings in the admin? Try that if not.

Now both options are `true`.

>Also, make sure that Twig caching is always turned on (disabling it just makes the site super slow without any benefits).

Done. Usually I turn off all cache for local development and turn it on in production. But still no `cache/twig` folder after this enable.

>Also check if the system.yaml file looks ok for you, there was a bug in the previous release where it was corrupted if you switched templates in admin.

I don't quite understand how it should look. I posted full `system.yaml` with last modifications in GH gist: https://gist.github.com/Sogl/787e5deceeac9c02ffddc896aa322d7b

**Comment by mahagr** [comment]
I fixed the bug when clearing cache, should become a non-issue after the next Grav release.

What comes to the cache folder, it really should have twig files or the site becomes really slow. Try if clean install has those files..?

**Comment by Sogl** [comment]
After update to Grav 1.7.9 and Admin 1.10.8 all works fine!
