### ISSUE TITLE
Problem on Scholar theme installation!

### ISSUE THREAD

**Issue by Balzac40** [getgrav/grav-plugin-admin#2114]
![image](https://user-images.githubusercontent.com/596556/114503041-fc47f380-9c2c-11eb-8879-8a11684e4fb6.png)

Trying to install Scholar Theme!

I can't no more use Grav!

Thanks

**Comment by mahagr** [comment]
Looks like there's a bad stream path. I cannot say more as I'd need to see where it comes from (trace).

**Comment by Balzac40** [comment]
First incident trace :
[2021-04-13 06:16:54] grav.CRITICAL: UniformResourceLocator: Absolute stream path with relative lookup not allowed () - Trace: #0 C:\xampp801\htdocs\grav\grav-admin\vendor\rockettheme\toolbox\ResourceLocator\src\UniformResourceLocator.php(449): RocketTheme\Toolbox\ResourceLocator\UniformResourceLocator->find('gantry-cache', '', false, false, false) #1 C:\xampp801\htdocs\grav\grav-admin\vendor\rockettheme\toolbox\ResourceLocator\src\UniformResourceLocator.php(332): RocketTheme\Toolbox\ResourceLocator\UniformResourceLocator->findCached('gantry-cache://', false, false, false) #2 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Common\Utils.php(133): RocketTheme\Toolbox\ResourceLocator\UniformResourceLocator->findResource('gantry-cache://', false) #3 C:\xampp801\htdocs\grav\grav-admin\user\plugins\static-generator\static-generator.php(89): Grav\Common\Utils::url('gantry-cache://') #4 C:\xampp801\htdocs\grav\grav-admin\vendor\symfony\event-dispatcher\EventDispatcher.php(264): Grav\Plugin\StaticGeneratorPlugin->onTwigAdminTemplatePaths(Object(RocketTheme\Toolbox\Event\Event), 'onTwigTemplateP...', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #5 C:\xampp801\htdocs\grav\grav-admin\vendor\symfony\event-dispatcher\EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onTwigTemplateP...', Object(RocketTheme\Toolbox\Event\Event)) #6 C:\xampp801\htdocs\grav\grav-admin\vendor\symfony\event-dispatcher\EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'onTwigTemplateP...', Object(RocketTheme\Toolbox\Event\Event)) #7 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Common\Grav.php(556): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(RocketTheme\Toolbox\Event\Event), 'onTwigTemplateP...') #8 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Common\Twig\Twig.php(103): Grav\Common\Grav->fireEvent('onTwigTemplateP...') #9 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Common\Processors\TwigProcessor.php(35): Grav\Common\Twig\Twig->init() #10 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(50): Grav\Common\Processors\TwigProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #11 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #12 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Common\Processors\AssetsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #13 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(50): Grav\Common\Processors\AssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #14 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #15 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Common\Processors\SchedulerProcessor.php(40): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #16 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(50): Grav\Common\Processors\SchedulerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #17 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #18 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Common\Processors\BackupsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #19 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(50): Grav\Common\Processors\BackupsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #20 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #21 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Common\Processors\TasksProcessor.php(69): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #22 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(50): Grav\Common\Processors\TasksProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #23 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #24 C:\xampp801\htdocs\grav\grav-admin\user\plugins\admin\classes\plugin\Router.php(65): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #25 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(50): Grav\Plugin\Admin\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #26 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #27 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Common\Processors\RequestProcessor.php(63): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #28 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(50): Grav\Common\Processors\RequestProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #29 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #30 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Common\Processors\ThemesProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #31 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(50): Grav\Common\Processors\ThemesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #32 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #33 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Common\Processors\PluginsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #34 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(50): Grav\Common\Processors\PluginsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #35 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #36 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Common\Processors\InitializeProcessor.php(130): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #37 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Common\Debugger.php(546): Grav\Common\Processors\InitializeProcessor::Grav\Common\Processors\{closure}() #38 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Common\Processors\InitializeProcessor.php(131): Grav\Common\Debugger->profile(Object(Closure)) #39 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(50): Grav\Common\Processors\InitializeProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #40 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #41 C:\xampp801\htdocs\grav\grav-admin\system\src\Grav\Common\Grav.php(295): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #42 C:\xampp801\htdocs\grav\grav-admin\index.php(58): Grav\Common\Grav->process() #43 {main} [] []

De : Matias Griese
Envoyé le :mardi 13 avril 2021 08:35
À : getgrav/grav-plugin-admin
Cc : Balzac40; Author
Objet :Re: [getgrav/grav-plugin-admin] Problem on Scholar theme installation! (#2114)

Looks like there's a bad stream path. I cannot say more as I'd need to see where it comes from (trace).

**Comment by mahagr** [comment]
The issue seems to come from Gantry.

**Comment by Balzac40** [comment]
Thank you, but I leave Grav now.
It was my third try, without success.
I do believe that Grav is avery good product, but for developers only.



De : Matias Griese
Envoyé le :mardi 13 avril 2021 13:05
À : getgrav/grav-plugin-admin
Cc : Balzac40; Author
Objet :Re: [getgrav/grav-plugin-admin] Problem on Scholar theme installation! (#2114)

The issue seems to come from Gantry.
