### ISSUE TITLE
Unauthorized and Page Media Errors

### ISSUE THREAD

**Issue by rwstone** [getgrav/grav-plugin-admin#334]
Hi, there.

This might be related to Wesley's issue (#333), but I'm in Chrome. My development environment is Windows.

I'm getting a variety of Unauthorized messages, including after saving a page. My Page Media boxes are also empty for all pages.

I did a fresh install of grav and the admin (so I just have antimatter and the sample home page). On that test site, toggling the option for the system `param_sep` turns my problems on and off.

More specifically, the errors are...

Failure to display page media with console error:

```
Internal Server Error -- GET http://localhost/grav-fresh/grav/admin/media/home.json/task;listmedia/admin-nonce:188eb182b7c5a64c6ff92a05401ab60d
```

And Unauthorized message at various times with grav.log message:

```
[2015-12-07 20:05:26] grav.CRITICAL: Template "media.html.twig" is not defined. - Trace: #0 C:\xampp\htdocs\grav\system\src\Grav\Common\Grav.php(157): Grav\Common\Twig\Twig->processSite(NULL) #1 C:\xampp\htdocs\grav\vendor\pimple\pimple\src\Pimple\Container.php(113 ): Grav\Common\Grav::Grav\Common\{closure}(Object(Grav\Common\Grav)) #2 C:\xampp\htdocs\grav\system\src\Grav\Common\Grav.php(258): Pimple\Container->offsetGet('output') #3 C:\xampp\htdocs\grav\index.php(37): Grav\Common\Grav->process() #4 {main} [] []
```

Thanks!

**Comment by rhukster** [comment]
I 'think' this is related to the nonce part of the URL.  Your on Windows and your param separator is `;`.

However, the nonce portion still has a `:` in it.  I think this is causing the internal server error.
