### ISSUE TITLE
Not able to edit pages through admin panel

### ISSUE THREAD

**Issue by simogeo** [getgrav/grav-plugin-admin#335]
Hi all,

 I get this error when opening a pages from admin panel : 

```
 Server Error

Sorry, something went terribly wrong!
0 - An exception has been thrown during the rendering of a template ("Invalid argument supplied for foreach()") in "pages.html.twig" at line 230.
```

and here is log entry : 

```
[2015-12-10 18:16:35] grav.CRITICAL: An exception has been thrown during the rendering of a template ("Invalid argument supplied for foreach()") in "pages.html.twig" at line 230. - Trace: #0 /home/simon/www/scop-grav/cache/twig/3b/3b5b5d10a20810ab19eddceeb85e84e14ab449815845a4225390e207d6075ffd.php(287): Twig_Template->displayBlock('content', Array, Array) #1 /home/simon/www/scop-grav/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_d9c69171b079a9b1f6ffaeacbe6d71b3ddec2d2e0314a5facbfd64a86f43eb4f->block_page(Array, Array) #2 /home/simon/www/scop-grav/cache/twig/3b/3b5b5d10a20810ab19eddceeb85e84e14ab449815845a4225390e207d6075ffd.php(45): Twig_Template->displayBlock('page', Array, Array) #3 /home/simon/www/scop-grav/vendor/twig/twig/lib/Twig/Template.php(381): __TwigTemplate_d9c69171b079a9b1f6ffaeacbe6d71b3ddec2d2e0314a5facbfd64a86f43eb4f->doDisplay(Array, Array) #4 /home/simon/www/scop-grav/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) #5 /home/simon/www/scop-grav/cache/twig/a9/a948cbed67dd3441a2ea8cc8aacd99cf5eadb6bb3adaedd76d7fe4e75cea8cfe.php(71): Twig_Template->display(Array, Array) #6 /home/simon/www/scop-grav/vendor/twig/twig/lib/Twig/Template.php(381): __TwigTemplate_633eeecfb84f2775f327dcb9bdb5f2835be02182f315ea8c5b6c61308e1b7979->doDisplay(Array, Array) #7 /home/simon/www/scop-grav/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) #8 /home/simon/www/scop-grav/vendor/twig/twig/lib/Twig/Template.php(366): Twig_Template->display(Array) #9 /home/simon/www/scop-grav/vendor/twig/twig/lib/Twig/Environment.php(347): Twig_Template->render(Array) #10 /home/simon/www/scop-grav/system/src/Grav/Common/Twig/Twig.php(322): Twig_Environment->render('pages.html.twig', Array) #11 /home/simon/www/scop-grav/system/src/Grav/Common/Grav.php(157): Grav\Common\Twig\Twig->processSite(NULL) #12 /home/simon/www/scop-grav/vendor/pimple/pimple/src/Pimple/Container.php(113): Grav\Common\Grav::Grav\Common\{closure}(Object(Grav\Common\Grav)) #13 /home/simon/www/scop-grav/system/src/Grav/Common/Grav.php(258): Pimple\Container->offsetGet('output') #14 /home/simon/www/scop-grav/index.php(37): Grav\Common\Grav->process() #15 {main} [] []
```

I cleared the cache but it does not change anything .... I use latest grav and plugin admin releases
Thanks for your help

**Comment by flaviocopes** [comment]
Hi, strange? Which web server are you using? Did you add custom blueprints to the theme, or are you using a standard theme?

**Comment by simogeo** [comment]
I use an Apache server.
I use a deliver-site skeleton based version.
I just found this link : https://github.com/getgrav/grav-skeleton-deliver-site/commit/2cd7228331a2f6db72df3a83758f3580af1f4e52. Not sure it is related to this issue. I crosspost.

Everything is working well when browsing another types of pages : `admin/info`, `admin/plugin`, `admin/pages`, are OK. But for example, browsing `/admin/pages/references/_portfolio` will trigger the error message.

**Comment by flaviocopes** [comment]
Can you PM me via Gitter your `user` folder to see if I can recreate it?

**Comment by simogeo** [comment]
Just opened a chat right now ... uploading files - nota familair with Gitter .... Ibut is getting ok

**Comment by simogeo** [comment]
Indeed, it works ! thanks
